FROM php:cli

# Install the mysql extension for php
RUN apt-get -y update
RUN apt-get -y install libjpeg-dev libpng-dev zlib1g-dev git
RUN /usr/local/bin/docker-php-ext-install mysqli gd mbstring

# Add the files to /srv
ADD ./piwik /srv/piwik

# Add the php.ini config file
ADD ./docker/piwik/php.ini /usr/local/etc/php/php.ini

# Set the working directory
WORKDIR /srv/piwik

# Install composer
RUN curl -sS https://getcomposer.org/installer | php 
RUN php composer.phar install

# Run piwik using the built in php runner
CMD php -S 0.0.0.0:8000 -t /srv/piwik